```{r install packages}
# install.packages("gridExtra")
# install.packages("relsurv")
# install.packages("flexsurv")
# install.packages("devtools") #If you don't have "devtools" installed already
# devtools::install_github("jamesjiadazhan/dietaryindex") # Install the package from GitHub
# install.packages("haven")
# install.packages("plyr")
# install.packages("dplyr")
# install.packages("arsenal")
# install.packages("survey")
# install.packages("ggplot2")
# install.packages("palmerpenguins")
# install.packages("tidyverse")
# install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R")))#暂定
# install.packages("lubridate")
# install.packages("fmsb")
# install.packages("ukbtools")
# install.packages("data.table")
# install.packages("Hmisc")
# install.packages("dplyr")
# # install.packagesy("h2o")
# install.packages("readxl")
# install.packages("purrr")
# install.packages("readr")
# install.packages("msm")
# install.packages("elect") #https://www.ucl.ac.uk/~ucakadl/ELECT/ELECTManual_version0_2.pdf
# install.packages("mice")
# install.packages("MatchThem")
# install.packages("MatchIt")
# install.packages("timeROC")
# install.packages("survival")
# install.packages("survivalROC")
# install.packages("pROC")
# install.packages("survminer")
# install.packages("table1")
# install.packages("boot")
# install.packages("knitr")
# install.packages("ezcox")
# install.packages("rms")
# install.packages("survival")
# install.packages("survminer")
# install.packages("forestplot")
# install.packages("stringr")
# install.packages("grid")
# install.packages("checkmate")
# install.packages("abind")
# install.packages("colourpicker")
# install.packages("cmprsk")
# install.packages("riskRegression")
# install.packages("pec")
# install.packages ("car")
# install.packages("autoReg")
# install.packages("epiR")
```

 
```{r load packages}
library(gridExtra)
library(relsurv)
library(flexsurv)
library(svglite)
library(dietaryindex)
library(haven)
library(plyr)
library(dplyr)
library(arsenal)
library(survey)
library(ggplot2)
library(palmerpenguins)
library(tidyverse)
library("lubridate")
library("fmsb")
library("ukbtools")
library("data.table")
library("Hmisc")
library("dplyr")
#library("h2o")
library("readxl")
library("purrr")
library("readr")
library("msm")
library("elect") #https://www.ucl.ac.uk/~ucakadl/ELECT/ELECTManual_version0_2.pdf
library("mice")
library("MatchThem")
library("MatchIt")
library("timeROC")
library("survival")
library("survivalROC")
library("pROC")
library("survminer")
library("table1")
library("boot")
library("knitr")
library("ezcox")
library("rms")
library("survival")
library("survminer")
library("forestplot")
library("stringr")
library("grid")
library("checkmate")
library("abind")
library("colourpicker")
library("cmprsk")
library("riskRegression")
library("pec")
library ("car")
library("autoReg")
library("epiR")
```


```{r unweighted and weighted baseline characteristics by CVH level}
data_table1 <- data_both_clean
fn_baseline(data_table1)
rm(data_table1)

data_table1 <- data_both_clean
fn_baseline_weighted(data_table1)
rm(data_table1)
```


```{r Load data_both_clean for Cox regression analysis}
# Use univariate Cox function
data_cox <- data_both_clean
fn_ezcox("survival_time", "death", "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc/all_cause_mortality_univariate_cox.csv")
rm(data_cox)

data_cox <- data_both_clean
fn_ezcox("survival_time", "CVD_mortality", "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc/CVD_specific_mortality_univariate_cox.csv")
rm(data_cox)

data_cox <- data_both_clean
fn_ezcox("survival_time", "cancer_mortality", "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc/cancer_specific_mortality_univariate_cox.csv")
rm(data_cox)

# Use multivariate Cox function
# All-cause mortality using multivariate Cox function
data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "death"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
fn_coxph(data_cox)
fn_coxph_weighted(data_cox)
rm(data_cox)

# Define TDI_sub
TDI_median <- median(data_both_clean$TDI, na.rm = TRUE)
data_both_clean$TDI_sub <- ifelse(data_both_clean$TDI > TDI_median, 0, ifelse(data_both_clean$TDI <= TDI_median, 1, NA))

# Define education_sub
data_both_clean$education_sub <- ifelse(data_both_clean$education <= 2, 0, 1)

# Define income_sub
data_both_clean$income_sub <- ifelse(data_both_clean$income <= 2, 0, 1)

data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "death"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
analyze_data(data_cox, "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc")

###################################################################
# CVD-specific mortality using multivariate Cox function
data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "CVD_mortality"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
fn_coxph(data_cox)
fn_coxph_weighted(data_cox)
rm(data_cox)

# Define TDI_sub
TDI_median <- median(data_both_clean$TDI, na.rm = TRUE)
data_both_clean$TDI_sub <- ifelse(data_both_clean$TDI > TDI_median, 0, ifelse(data_both_clean$TDI <= TDI_median, 1, NA))

# Define education_sub
data_both_clean$education_sub <- ifelse(data_both_clean$education <= 2, 0, 1)

# Define income_sub
data_both_clean$income_sub <- ifelse(data_both_clean$income <= 2, 0, 1)

data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "CVD_mortality"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
analyze_data(data_cox, "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc")

############################################################
# Cancer-specific mortality using multivariate Cox function
data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "cancer_mortality"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
fn_coxph(data_cox)
fn_coxph_weighted(data_cox)
rm(data_cox)

# Define TDI_sub
TDI_median <- median(data_both_clean$TDI, na.rm = TRUE)
data_both_clean$TDI_sub <- ifelse(data_both_clean$TDI > TDI_median, 0, ifelse(data_both_clean$TDI <= TDI_median, 1, NA))

# Define education_sub
data_both_clean$education_sub <- ifelse(data_both_clean$education <= 2, 0, 1)

# Define income_sub
data_both_clean$income_sub <- ifelse(data_both_clean$income <= 2, 0, 1)

data_cox <- data_both_clean
names(data_cox)[names(data_cox) == "age"] <- "age"
names(data_cox)[names(data_cox) == "survival_time"] <- "time"
names(data_cox)[names(data_cox) == "cancer_mortality"] <- "status"
data_cox <- data_cox %>%
  mutate(
    CVH_level = case_when(
      total_score < 60 ~ "Low CVH", # Reference
      total_score >= 60 & total_score < 80 ~ "Moderate CVH",
      total_score >= 80 ~ "High CVH"
    ),
    CVH_level = factor(
      CVH_level, 
      levels = c("Low CVH", "Moderate CVH", "High CVH")
    )
  )
analyze_data(data_cox, "C:/Users/pc/Desktop/yfr/result_nhanes/result/le10_cc")
```


```{r Calculation of biological ages (KDM-BA, PhenoAge)}
###################################################################################
# REF: https://gitcode.com/gh_mirrors/bi/BioAge
# REF: https://rdrr.io/github/dayoonkwon/BioAge/
# REF: https://zenodo.org/records/7777437
###################################################################################
#install.packages("devtools")
#devtools::install_github("dayoonkwon/BioAge")
library(BioAge)

## KDM-BA
#Train algorithms in NHANES III and project biological ageing measures in NHANES IV
biomarkers <- c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun")

#Train using the NHANES III
train = kdm_calc(NHANES3,
                 biomarkers = c("fev","sbp","totchol","hba1c","albumin",
                 "creat","lncrp","alp","bun"))

#Project into the NHANES IV
kdm = kdm_calc(NHANES4,
               biomarkers = c("fev","sbp","totchol","hba1c","albumin",
               "creat","lncrp","alp","bun"),
               fit = train$fit,
               s_ba2 = train$fit$s_ba2)

# Project KDM-BA to kdm_US using NHANES III (trained separately by sex)
kdm_fem <- kdm_calc(
  data = cleaned_NHANES %>% filter(sex == 0),
  biomarkers = c("fev", "sbp", "totchol", "hba1c", "albumin", "creat", "lncrp", "alp", "bun"),
  fit = kdm$fit$female,
  s_ba2 = kdm$fit$female$s_b2
)

kdm_male <- kdm_calc(
  data = cleaned_NHANES %>% filter(sex == 1),
  biomarkers = c("fev", "sbp", "totchol", "hba1c", "albumin", "creat", "lncrp", "alp", "bun"),
  fit = kdm$fit$male,
  s_ba2 = kdm$fit$male$s_b2
)
# Combine male and female datasets
kdm_US <- rbind(kdm_fem$data, kdm_male$data)

## PhenoAge
#Train algorithms in NHANES III and project biological ageing measures in NHANES IV
biomarkers <- c("albumin_gL","lymph","mcv","glucose_mmol","rdw","creat_umol","lncrp","alp","wbc")

#Train using the NHANES III
train = phenoage_calc(NHANES3,
                      biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                      "rdw","creat_umol","lncrp","alp","wbc"))

#Project into the NHANES IV
phenoage = phenoage_calc(NHANES4,
                         biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                         "rdw","creat_umol","lncrp","alp","wbc"),
                         fit = train$fit)
#Train using the NHANES III
train = phenoage_calc(NHANES3,
                      biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                      "rdw","creat_umol","lncrp","alp","wbc"))
#Project into the merged_NHANES
phenoage = phenoage_calc(cleaned_NHANES,
                         biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                         "rdw","creat_umol","lncrp","alp","wbc"),
                         fit = train$fit)
#Extract phenoage dataset
pheno_US = phenoage$data

```


```{r Weighted logistic regression model}
# Create survey design object
# Using WTDR2D (2-year interview weights) as weight variable
# SDMVSTRA as strata variable, and SDMVPSU as cluster variable
nhanes_design <- svydesign(
  id = ~SDMVPSU,          # Cluster variable
  strata = ~SDMVSTRA,     # Strata variable 
  weights = ~WTDR2D,      # Weight variable
  data = data_US,         # Dataset
  nest = TRUE             # Set TRUE if strata are nested
)

# Perform weighted logistic regression analysis
model <- svyglm(
  # Model formula with predictors
  kdm_AA_binary ~ age + sex + TDI + ethnicity + education + income + family_history + CVH_level,  
  design = nhanes_design,         # Survey design object
  family = quasibinomial()        # Specify logistic regression
)

# View model results
summary(model)
```


``` {r life expectancy}
# install.packages("relsurv")
# install.packages("flexsurv")
library(relsurv)
library(flexsurv)

sur <- data_both_clean
fn_le(sur)
rm(sur)
```



```{r 模型比较}
# REF: https://blog.csdn.net/Dr_long1996/article/details/135588760
# REF: https://www.jingege.wang/2022/09/23/time-auc%e5%92%8ctime-c-index%e7%bb%98%e5%9b%be/
# 安装 BiocManager 包
#install.packages("BiocManager")
# 使用 BiocManager 安装 survcomp 包
#BiocManager::install("survcomp")
#install.packages("compareC")
library(survcomp)
library(compareC)
library(survival)
library(rms) 
library(pec)

data_nhanes <- data_both_clean
data_nhanes <- data_nhanes %>%
  mutate(
    age_group = case_when(
        age < 60 ~ "<60 years", # Reference
        age >= 60 ~ "≥60 years"),
    age_group = factor(age_group, levels = c("<60 years", "≥60 years")),
    sex = factor(sex, levels = c(1, 0), labels = c("Male", "Female")),
    ethnicity = factor(ethnicity, levels = c(1, 2, 3, 4, 5),
                       labels = c("Mexican American", "Other Hispanic", "Non-Hispanic White", "Non-Hispanic Black", "Other race—including multi-racial")),
    education = factor(education, levels = c(1, 2, 3, 4, 5),
                       labels = c("Less Than 9th Grade", "9-11th Grade (Includes 12th grade with no diploma)", "High School Grad/GED or Equivalent", "Some College or AA degree", "College Graduate or above")),
    income = factor(income, levels = c(1, 2, 3, 4),
                    labels = c("$0 to $14,999", "$15,000 to $34,999", "$35,000 to $64,999", "$65,000 and Over")),
    family_history = factor(family_history, levels = c(0, 1), labels = c("No", "Yes")))

## All-cause mortality
data_nhanes <- data_nhanes %>% dplyr::rename(time = survival_time)
data_nhanes <- data_nhanes %>% dplyr::rename(status = death)
## CVD-specific mortality
data_nhanes <- data_nhanes %>% dplyr::rename(time = survival_time)
data_nhanes <- data_nhanes %>% dplyr::rename(status = CVD_mortality)
## cancer-specific mortality
data_nhanes <- data_nhanes %>% dplyr::rename(time = survival_time)
data_nhanes <- data_nhanes %>% dplyr::rename(status = cancer_mortality)

#LE8
model_LE8 <- coxph(Surv(time,status)~age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score, data=data_nhanes, x=TRUE)
Cindex_LE8 <- summary(model_LE8)$concordance
Cindex_LE8
#LC9
model_LC9 <- coxph(Surv(time,status)~age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+mental_health_score, data=data_nhanes, x=TRUE)
Cindex_LC9 <- summary(model_LC9)$concordance
Cindex_LC9
#LE9
model_LE9 <- coxph(Surv(time,status)~age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score, data=data_nhanes, x=TRUE)
Cindex_LE9 <- summary(model_LE9)$concordance
Cindex_LE9
#LE10
model_LE10 <- coxph(Surv(time,status)~age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score+mental_health_score, data=data_nhanes, x=TRUE)
Cindex_LE10 <- summary(model_LE10)$concordance
Cindex_LE10

#####################################################################
# Calculate C-indexes with survcomp package
#####################################################################
Cindex_LE8 <- concordance.index(x=predict(model_LE8),
                                 surv.time=data_nhanes$time,
                                 surv.event=data_nhanes$status,
                                 method="noether")
Cindex_LE8

#LC9
Cindex_LC9 <- concordance.index(x=predict(model_LC9),
                                 surv.time=data_nhanes$time,
                                 surv.event=data_nhanes$status,
                                 method="noether")
Cindex_LC9

#LE9
Cindex_LE9 <- concordance.index(x=predict(model_LE9),
                                 surv.time=data_nhanes$time,
                                 surv.event=data_nhanes$status,
                                 method="noether")
Cindex_LE9

#LE10
Cindex_LE10 <- concordance.index(x=predict(model_LE10),
                                 surv.time=data_nhanes$time,
                                 surv.event=data_nhanes$status,
                                 method="noether")
Cindex_LE10

cindex.comp1 <- cindex.comp(Cindex_LC9, Cindex_LE8)
cindex.comp2 <- cindex.comp(Cindex_LE9, Cindex_LE8)
cindex.comp3 <- cindex.comp(Cindex_LE10, Cindex_LE8)

p.value_decimal1 <- format(cindex.comp1$p.value, scientific = FALSE)
p.value_decimal2 <- format(cindex.comp2$p.value, scientific = FALSE)
p.value_decimal3 <- format(cindex.comp3$p.value, scientific = FALSE)

#####################################################################
# Calculate time-dependent AUC
#####################################################################
pred_LE8 <- predict(model_LE8, type = "lp")
pred_LE9 <- predict(model_LE9, type = "lp")
pred_LC9 <- predict(model_LC9, type = "lp")
pred_LE10 <- predict(model_LE10, type = "lp")

time_points <- seq(0, 15, by = 0.1)
time_roc_LE8 <- timeROC(T = data_nhanes$time, delta = data_nhanes$status, marker = pred_LE8, cause = 1, times = time_points)
time_roc_LC9 <- timeROC(T = data_nhanes$time, delta = data_nhanes$status, marker = pred_LC9, cause = 1, times = time_points)
time_roc_LE9 <- timeROC(T = data_nhanes$time, delta = data_nhanes$status, marker = pred_LE9, cause = 1, times = time_points)
time_roc_LE10 <- timeROC(T = data_nhanes$time, delta = data_nhanes$status, marker = pred_LE10, cause = 1, times = time_points)

# Extract AUC values
auc1 <- time_roc_LE8$AUC
auc2 <- time_roc_LC9$AUC
auc3 <- time_roc_LE9$AUC
auc4 <- time_roc_LE10$AUC

df_auc <- data.frame(
  Time = rep(time_points, 4),  
  AUC = c(auc1, auc2, auc3, auc4),  
  Model = c(rep("LE8", length(time_points)), rep("LC9", length(time_points)), rep("LE9", length(time_points)), rep("LE10", length(time_points)))
)
print(df_auc)

# Fit the logistic model for KDM-BA acceleration
# LE8
model1 <- glm(kdm_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score, data = kdm_US, family = binomial, x = TRUE,y = TRUE)
# LE8+mental health score
model2 <- glm(kdm_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+mental_health_score, data = kdm_US, family = binomial, x = TRUE,y = TRUE)
# LE8+alcohol consumption score
model3 <- glm(kdm_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score, data = kdm_US, family = binomial, x = TRUE,y = TRUE)
# LE10
model4 <- glm(kdm_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score+mental_health_score, data = kdm_US, family = binomial, x = TRUE,y = TRUE)

# Calculate prediction values
kdm_US$predvalue1 <- predict(model1)
kdm_US$predvalue2 <- predict(model2)
kdm_US$predvalue3 <- predict(model3)
kdm_US$predvalue4 <- predict(model4)

# Fit ROC
modelROC1 <- roc(kdm_US$kdm_AA_binary, kdm_US$predvalue1)
auc1 <- auc(modelROC1)
ci1 <- ci(auc1)
modelROC2 <- roc(kdm_US$kdm_AA_binary, kdm_US$predvalue2)
auc2 <- auc(modelROC2)
ci2 <- ci(auc2)
modelROC3 <- roc(kdm_US$kdm_AA_binary, kdm_US$predvalue3)
auc3 <- auc(modelROC3)
ci3 <- ci(auc3)
modelROC4 <- roc(kdm_US$kdm_AA_binary, kdm_US$predvalue4)
auc4 <- auc(modelROC4)
ci4 <- ci(auc4)

# Calculate the difference between two models using the roc.test function in the pROC package
roc_test_result1 <- roc.test(modelROC1, modelROC2)
roc_test_result2 <- roc.test(modelROC1, modelROC3)
roc_test_result3 <- roc.test(modelROC1, modelROC4)


# Fit the logistic model for PhenoAge acceleration
# LE8
model1 <- glm(pheno_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score, data = pheno_US, family = binomial, x = TRUE,y = TRUE)
# LE8+mental health score
model2 <- glm(pheno_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+mental_health_score, data = pheno_US, family = binomial, x = TRUE,y = TRUE)
# LE8+alcohol consumption score
model3 <- glm(pheno_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score, data = pheno_US, family = binomial, x = TRUE,y = TRUE)
# LE10
model4 <- glm(pheno_AA_binary ~ age+sex+TDI+ethnicity+education+income+family_history+physical_activity_score+smoke_score+HDI_score+sleep_score+BMI_score+BL_score+BG_score+BP_score+alcohol_score+mental_health_score, data = pheno_US, family = binomial, x = TRUE,y = TRUE)

# Calculate prediction values
pheno_US$predvalue1 <- predict(model1)
pheno_US$predvalue2 <- predict(model2)
pheno_US$predvalue3 <- predict(model3)
pheno_US$predvalue4 <- predict(model4)

# Fit ROC
modelROC1 <- roc(pheno_US$pheno_AA_binary, pheno_US$predvalue1)
auc1 <- auc(modelROC1)
ci1 <- ci(auc1)
modelROC2 <- roc(pheno_US$pheno_AA_binary, pheno_US$predvalue2)
auc2 <- auc(modelROC2)
ci2 <- ci(auc2)
modelROC3 <- roc(pheno_US$pheno_AA_binary, pheno_US$predvalue3)
auc3 <- auc(modelROC3)
ci3 <- ci(auc3)
modelROC4 <- roc(pheno_US$pheno_AA_binary, pheno_US$predvalue4)
auc4 <- auc(modelROC4)
ci4 <- ci(auc4)

# Calculate the difference between two models using the roc.test function in the pROC package
roc_test_result1 <- roc.test(modelROC1, modelROC2)
roc_test_result2 <- roc.test(modelROC1, modelROC3)
roc_test_result3 <- roc.test(modelROC1, modelROC4)
```

