```{r load packages}
#install.packages("devtools")
#devtools::install_github("dayoonkwon/BioAge")
library(BioAge)
```


```{r KDM-BA——NHANES}
#Train algorithms in NHANES III and project biological aging measures in NHANES IV
biomarkers <- c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun")

#Train using the NHANES III
train = kdm_calc(NHANES3,
                 biomarkers = c("fev","sbp","totchol","hba1c","albumin",
                 "creat","lncrp","alp","bun"))

#Project into the NHANES IV
kdm = kdm_calc(NHANES4,
               biomarkers = c("fev","sbp","totchol","hba1c","albumin",
               "creat","lncrp","alp","bun"),
               fit = train$fit,
               s_ba2 = train$fit$s_ba2)

#Extract KDM dataset
data = kdm$data


```


```{r KDM-BA}
#Projecting KDM bioage into new data using NHANES III (separate training for gender)
kdm_fem = kdm_calc(data = data_KDM %>%
                        filter (gender == 0),
                      biomarkers=c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun"),
                   fit = kdm$fit$female,
                   s_ba2 = kdm$fit$female$s_b2)

kdm_male = kdm_calc(data = data_KDM %>%
                         filter (gender == 1),
                       biomarkers=c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun"),
                   fit = kdm$fit$male,
                   s_ba2 = kdm$fit$male$s_b2)

#Combine the datasets
kdm_data = rbind(kdm_fem$data, kdm_male$data)

```


```{r PhenoAge——NHANES}
#Train algorithms in NHANES III and project biological aging measures in NHANES IV
biomarkers <- c("albumin_gL","lymph","mcv","glucose_mmol","rdw","creat_umol","lncrp","alp","wbc")

#Train using the NHANES III
train = phenoage_calc(NHANES3,
                      biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                      "rdw","creat_umol","lncrp","alp","wbc"))

#Project into the NHANES IV
phenoage = phenoage_calc(NHANES4,
                         biomarkers = c("albumin_gL","lymph","mcv","glucose_mmol",
                         "rdw","creat_umol","lncrp","alp","wbc"),
                         fit = train$fit)

#Extract phenoage dataset
data = phenoage$data

```


```{r PhenoAge}
#Projecting phenoage into new data using NHANES III
biomarkers <- c("albumin_gL","lymph","mcv","glucose_mmol","rdw","creat_umol","lncrp","alp","wbc")
descriptions <- lapply(biomarkers, function(var) skim(data_BA[[var]]))

phenoage = phenoage_calc(data_BA,
                         biomarkers = biomarkers, 
                         fit = train$fit, 
                         orig = FALSE)
#Extract phenoage dataset
df = phenoage$data

```

